name: ECMP
description: Spigot plugin for the Enjin Coin Minecraft Framework, a platform for game assets on the Ethereum block-chain.
version: @version@-spigot
authors: [Evan "Favorlock" Lindsay, Damien Gallagher, Tobias Drewry, Enjin Coin Team]
website: https://enjincoin.io
main: com.enjin.ecmp.spigot.EnjPlugin
softdepend: [Vault, PlaceholderAPI]
api-version: 1.13
commands:
  enj:
    description: Reference command for ECMP.
permissions:
  ecmp.*:
    default: op
    children:
      ecmp.player: true
      ecmp.conf: true
  ecmp.conf:
    default: false
    children:
      ecmp.conf.set: true
      ecmp.conf.reload: true
  ecmp.player:
    default: true
    children:
      ecmp.root: true
      ecmp.balance: true
      ecmp.help: true
      ecmp.link: true
      ecmp.send: true
      ecmp.trade: true
      ecmp.unlink: true
      ecmp.wallet: true
  ecmp.trade:
    children:
      ecmp.trade.invite: true
      ecmp.trade.accept: true
      ecmp.trade.decline: true