name: ECMP
description: Spigot plugin for the Enjin Coin Minecraft Framework, a platform for game assets on the Ethereum block-chain.
version: @version@-spigot
authors: [Evan "Favorlock" Lindsay, Damien Gallagher, Tobias Drewry, Enjin Coin Team]
website: https://enjincoin.io
main: com.enjin.ecmp.spigot.EnjPlugin
softdepend: [Vault, PlaceholderAPI]
api-version: 1.13
commands:
  enj:
    description: Reference command for ECMP.
permissions:
  ecmp.root:
    default: true
  ecmp.balance:
    default: true
  ecmp.help:
    default: true
  ecmp.link:
    default: true
  ecmp.send:
    default: true
  ecmp.trade:
    default: true
    children:
      ecmp.trade.invite: true
      ecmp.trade.accept: true
      ecmp.trade.decline: true
  ecmp.unlink:
    default: true
  ecmp.wallet:
    default: true